name: Update EPG
on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v6
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v6
        with:
         repository: iptv-org/epg
         path: iptv-org-epg

      - name: update EPG
        run: sh EPG/epg-pt.sh

      - name: setup git config
        run: |
          git config user.name "🤖 R2-D2"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: commit
        run: |
          git pull --rebase origin main
          git add EPG/
          git commit -m "Update EPG"
          git push origin main
